# fragment_features.py (or add to pattern_features.py)

from typing import Dict, List, Any
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Assumes BaseFeature is importable from its location
# from ..base_feature import BaseFeature
# If placing in pattern_features.py, use:
from ..base_feature import BaseFeature

class TrypticTerminalFeature(BaseFeature):
    """
    Identifies if the peptide fragment likely represents a C-terminal
    fragment generated by trypsin cleavage (ends in K or R, not preceded by P).
    """

    def __init__(self):
        super().__init__()
        self.raw_columns = ['is_tryptic_C_terminal']
        self.ml_columns = ['is_tryptic_C_terminal'] # Boolean 0/1 feature

    def calculate_raw(self, sequence: str) -> Dict[str, Any]:
        """Checks if the sequence ends with a typical tryptic cleavage site."""
        is_tryptic_c_term = False
        if len(sequence) >= 1:
            last_aa = sequence[-1]
            if last_aa in ('K', 'R'):
                # Check if preceded by Proline (only if long enough)
                if len(sequence) >= 2:
                    if sequence[-2] != 'P':
                        is_tryptic_c_term = True
                else:
                    # If only 1 AA and it's K/R, consider it tryptic? Debatable, let's say yes for now.
                    is_tryptic_c_term = True
        raw_data = {'is_tryptic_C_terminal': is_tryptic_c_term}
        self.raw_data = raw_data
        return raw_data

    def calculate_ml_ready(self, sequence: str) -> Dict[str, float]:
        """Converts boolean to float 0.0 or 1.0."""
        if hasattr(self, 'raw_data') and self.raw_data is not None:
             raw = self.raw_data
        else:
             raw = self.calculate_raw(sequence)

        ml_data = {'is_tryptic_C_terminal': float(raw['is_tryptic_C_terminal'])}
        self.ml_data = ml_data
        return ml_data

    def plot_distributions(self, raw_data: pd.DataFrame, ml_data: pd.DataFrame) -> plt.Figure:
        """Plots the distribution of the boolean feature."""
        fig, ax = plt.subplots(1, 1, figsize=(6, 5))

        if not ml_data.empty and 'is_tryptic_C_terminal' in ml_data.columns:
            counts = ml_data['is_tryptic_C_terminal'].value_counts().sort_index()
            sns.barplot(x=counts.index.map({0.0: 'False', 1.0: 'True'}), y=counts.values, ax=ax, palette="viridis")
            ax.set_title('Is Likely Tryptic C-Terminal Fragment?')
            ax.set_ylabel('Count')
            ax.set_xlabel('')
        else:
            ax.text(0.5, 0.5, 'No data available', ha='center', va='center')
            ax.set_title('Is Likely Tryptic C-Terminal Fragment?')

        plt.tight_layout()
        return fig


class InternalCleavageSitesFeature(BaseFeature):
    """
    Counts potential internal trypsin cleavage sites (K/R not followed by P)
    and resistant sites (K/R followed by P) within the fragment sequence.
    More internal sites might lead to further degradation.
    """

    def __init__(self):
        super().__init__()
        self.raw_columns = ['internal_KR_cleavable_count', 'internal_KP_RP_resistant_count']
        self.ml_columns = ['internal_KR_cleavable_per_res_log', 'internal_KP_RP_resistant_per_res_log']

    def calculate_raw(self, sequence: str) -> Dict[str, Any]:
        """Counts internal cleavable (K/R not P) and resistant (KP/RP) sites."""
        cleavable_count = 0
        resistant_count = 0
        # Iterate up to the second-to-last residue to check pairs
        for i in range(len(sequence) - 1):
            current_aa = sequence[i]
            next_aa = sequence[i+1]
            if current_aa in ('K', 'R'):
                if next_aa == 'P':
                    resistant_count += 1
                else:
                    cleavable_count += 1
        # Note: Doesn't count the final K/R if sequence ends there, as that's handled by TrypticTerminalFeature

        raw_data = {
            'internal_KR_cleavable_count': cleavable_count,
            'internal_KP_RP_resistant_count': resistant_count
        }
        self.raw_data = raw_data
        return raw_data

    def calculate_ml_ready(self, sequence: str) -> Dict[str, float]:
        """Normalizes counts by length and applies log1p transformation."""
        if hasattr(self, 'raw_data') and self.raw_data is not None:
            raw = self.raw_data
        else:
            raw = self.calculate_raw(sequence)

        length = len(sequence)
        # Use length-1 for normalization denominator, as we count pairs/sites between residues
        # Avoid division by zero for single-AA sequences
        norm_factor = max(1, length -1) # Use length if length=1, else length-1

        cleavable_per_res = raw['internal_KR_cleavable_count'] / norm_factor
        resistant_per_res = raw['internal_KP_RP_resistant_count'] / norm_factor

        ml_data = {
            # Log1p transform is good for counts that can be zero
            'internal_KR_cleavable_per_res_log': np.log1p(cleavable_per_res),
            'internal_KP_RP_resistant_per_res_log': np.log1p(resistant_per_res)
        }
        self.ml_data = ml_data
        return ml_data


class HydrolysisProneBondFeature(BaseFeature):
    """
    Counts the number of Asp-Pro (DP) dipeptides, known to be
    susceptible to acid hydrolysis, potentially indicating fragment instability.
    """
    def __init__(self):
        super().__init__()
        self.raw_columns = ['asp_pro_count']
        self.ml_columns = ['asp_pro_per_res_log']

    def calculate_raw(self, sequence: str) -> Dict[str, Any]:
        """Counts occurrences of 'DP'."""
        dp_count = sequence.count('DP')
        raw_data = {'asp_pro_count': dp_count}
        self.raw_data = raw_data
        return raw_data

    def calculate_ml_ready(self, sequence: str) -> Dict[str, float]:
        """Normalizes count by length and applies log1p transformation."""
        if hasattr(self, 'raw_data') and self.raw_data is not None:
            raw = self.raw_data
        else:
            raw = self.calculate_raw(sequence)

        length = len(sequence)
        norm_factor = max(1, length - 1) # Normalize by number of possible dipeptide positions
        dp_per_res = raw['asp_pro_count'] / norm_factor

        ml_data = {
            'asp_pro_per_res_log': np.log1p(dp_per_res)
        }
        self.ml_data = ml_data
        return ml_data

# --- How to Integrate ---
# 1. Save this code: Put these classes into a new file like
#    `peptide_templating/features/non_folding/fragment_features.py`
#    or add them to an existing one like `pattern_features.py`.
#
# 2. Import them: In `peptide_templating/features/non_folding/__init__.py`, add:
#    from .fragment_features import ( # Or from .pattern_features import ...
#        TrypticTerminalFeature,
#        InternalCleavageSitesFeature,
#        HydrolysisProneBondFeature,
#    )
#
# 3. Add to PeptideFeatures: In `peptide_templating/features/peptide_features.py`,
#    add instances of these new classes to the `self.features` dictionary:
#    self.features = {
#        # ... other features ...
#        'tryptic_terminal': TrypticTerminalFeature(),
#        'internal_cleavage': InternalCleavageSitesFeature(),
#        'hydrolysis_prone': HydrolysisProneBondFeature(),
#    }
#    Also, add them to the `self.feature_groups` dictionary, perhaps under 'pattern' or a new 'fragment' group:
#    self.feature_groups = {
#        # ... other groups ...
#        'fragment_props': ['tryptic_terminal', 'internal_cleavage', 'hydrolysis_prone'],
#    }
#
# 4. Recalculate Features: Rerun the feature calculation pipeline
#    (e.g., `python -m peptide_ml.features.peptide_features --calc --save ...`)
#    to generate new `features_raw.csv` and `features_ml.csv` files containing these features.
#
# 5. Update Notebook: Ensure your notebook loads the *new* feature file and includes these
#    new features when defining `feature_columns_all` before splitting and modeling.